spring:
  application:
    name: zuul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.102:3306/easytocloud?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
    timeout: 5000

server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
  instance:
    prefer-ip-address: true    #表面模块之间允许跨域

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.yingtongquan.system.*.

zuul:
  host:
    max-per-route-connections: 1000
    max-total-connections: 1000
  semaphore:
    max-semaphores: 200
  routes:
    yingtongquan_system:
      path: /system/**
      serviceId: yingtongquan_system
    yingtongquan_employees:
      path: /employees/**
      serviceId: yingtongquan_employees
    yingtongquan_order:
      path: /order/**
      serviceId: yingtongquan_order
    startcommon:
      path: /address/**
      serviceId: startcommon
    yingtongquan_customer:
      path: /user/**
      serviceId: yingtongquan_customer